import { defineConfig, type Plugin } from 'vitest/config';
import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = 'docs';

/**
 * Reads docs/data.js before Vite wipes the outDir, then re-emits it as a
 * bundle asset so it survives emptyOutDir. This lets data.js live only in
 * docs/ (generated by the Python scraper) without needing a public/ copy.
 */
function preserveDataJs(): Plugin {
  const dataJsPath = path.join(OUT_DIR, 'data.js');
  const content = fs.existsSync(dataJsPath) ? fs.readFileSync(dataJsPath, 'utf-8') : null;
  return {
    name: 'preserve-data-js',
    generateBundle() {
      if (content) {
        this.emitFile({ type: 'asset', fileName: 'data.js', source: content });
      } else {
        this.warn('docs/data.js not found — run the Python scraper first to generate it');
      }
    },
  };
}

/**
 * Ensures the built HTML is compatible with file:// protocol:
 * - Removes type="module" and crossorigin (Chrome blocks ES module scripts on file://)
 * - Moves bundle.js to end of <body>, after data.js, so window.MSX_DATA is set first
 */
function fileProtocolCompat(): Plugin {
  return {
    name: 'file-protocol-compat',
    transformIndexHtml(html: string): string {
      // Remove the bundle script from <head> (where Vite injects it)
      let out = html.replace(
        /<script type="module" crossorigin src="\.\/bundle\.js"><\/script>\s*/g,
        ''
      );
      // Fix absolute /data.js path → relative ./data.js for file:// compatibility
      out = out.replace('src="/data.js"', 'src="./data.js"');
      // Append bundle at the end of <body>, after data.js
      return out.replace('</body>', '  <script src="./bundle.js"></script>\n  </body>');
    },
  };
}

export default defineConfig({
  base: './',
  publicDir: false,
  plugins: [preserveDataJs(), fileProtocolCompat()],
  build: {
    outDir: OUT_DIR,
    emptyOutDir: true,
    rollupOptions: {
      output: {
        format: 'iife',
        name: 'MSXApp',
        entryFileNames: 'bundle.js',
        chunkFileNames: 'bundle.js',
        assetFileNames: '[name][extname]',
      },
    },
  },
  test: {
    environment: 'jsdom',
    passWithNoTests: true,
  },
});
