import { defineConfig, type Plugin } from 'vitest/config';
import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = 'docs';

/**
 * Reads docs/data.js before Vite wipes the outDir, then re-emits it as a
 * bundle asset so it survives emptyOutDir. This lets data.js live only in
 * docs/ (generated by the Python scraper) without needing a public/ copy.
 */
function preserveDataJs(): Plugin {
  const dataJsPath = path.join(OUT_DIR, 'data.js');
  const content = fs.existsSync(dataJsPath) ? fs.readFileSync(dataJsPath, 'utf-8') : null;
  return {
    name: 'preserve-data-js',
    generateBundle() {
      if (content) {
        this.emitFile({ type: 'asset', fileName: 'data.js', source: content });
      } else {
        this.warn('docs/data.js not found — run the Python scraper first to generate it');
      }
    },
  };
}

/**
 * Ensures the built HTML is compatible with file:// protocol:
 * - Removes type="module" and crossorigin (Chrome blocks ES module scripts on file://)
 * - Injects data.js and bundle.js at end of <body> so window.MSX_DATA is set before the app runs
 */
function fileProtocolCompat(): Plugin {
  return {
    name: 'file-protocol-compat',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler(html: string): string {
        // Remove the bundle script from <head> (where Vite injects it)
        let out = html.replace(
          /<script[^>]*type="module"[^>]*src="\.\/bundle\.js"[^>]*><\/script>\s*/g,
          ''
        );
        // Inject data.js then bundle.js at end of <body>, so window.MSX_DATA is set first
        return out.replace('</body>', '  <script src="./data.js"></script>\n  <script src="./bundle.js"></script>\n  </body>');
      },
    },
  };
}

/**
 * Dev server only: serves docs/data.js (read fresh on every request, so a
 * scraper re-run shows up on reload) and loads it before the app module.
 */
function devDataJs(): Plugin {
  const dataJsPath = path.join(OUT_DIR, 'data.js');
  return {
    name: 'dev-data-js',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/data.js', (_req, res) => {
        if (!fs.existsSync(dataJsPath)) {
          res.statusCode = 404;
          res.end('// docs/data.js not found — run the Python scraper first');
          return;
        }
        res.setHeader('Content-Type', 'text/javascript; charset=utf-8');
        res.setHeader('Cache-Control', 'no-store');
        res.end(fs.readFileSync(dataJsPath));
      });
    },
    transformIndexHtml(html: string): string {
      return html.replace('<script type="module"', '<script src="/data.js"></script>\n    <script type="module"');
    },
  };
}

export default defineConfig({
  root: 'src',
  base: './',
  publicDir: false,
  plugins: [preserveDataJs(), fileProtocolCompat(), devDataJs()],
  build: {
    outDir: path.resolve(OUT_DIR),
    emptyOutDir: true,
    rollupOptions: {
      output: {
        format: 'iife',
        name: 'MSXApp',
        entryFileNames: 'bundle.js',
        chunkFileNames: 'bundle.js',
        assetFileNames: '[name][extname]',
      },
    },
  },
  test: {
    // Vite's root is src/, but tests live in tests/web/ — resolve from the repo root.
    root: path.resolve(),
    include: ['tests/web/**/*.test.ts'],
    environment: 'jsdom',
  },
});
